<?php
// This template renders the main Bali 3D Explorer UI as used in the original index.html
?>
<div class="bali3d-explorer">
    <main>
        <aside class="destination-sidebar">
            <div class="search-container">
                <input type="text" placeholder="Search destinations...">
                <button class="search-btn" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0 1 11 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 0 1-1.969 5.617zm-2.006-.742A6.977 6.977 0 0 0 18 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 0 0 4.875-1.975l.15-.15z"/></svg>
                </button>
            </div>
            <div class="sidebar-content">
                <div class="categories">
                    <h2>Categories</h2>
                    <ul>
                        <li><a href="#featured" class="active">Featured Attractions</a></li>
                        <li><a href="#beaches">Top Beaches</a></li>
                        <li><a href="#beach-clubs">Beach Clubs</a></li>
                        <li><a href="#water-sports">Water Sports</a></li>
                        <li><a href="#cultural">Cultural Sites</a></li>
                        <li><a href="#cultural-experiences">Cultural Experiences</a></li>
                        <li><a href="#traditional-villages">Balinese Traditional Villages</a></li>
                    </ul>
                </div>
                <div class="destination-list">
                    <!-- Destination items will be dynamically generated by JS -->
                </div>
            </div>
        </aside>
        <section class="map-container">
            <div id="map"></div>
            <div class="map-controls">
                <button class="control-btn zoom-in" aria-label="Zoom In">+</button>
                <button class="control-btn zoom-out" aria-label="Zoom Out">-</button>
                <button class="control-btn rotate" aria-label="Rotate">⟳</button>
                <button class="control-btn reset" aria-label="Reset">⭯</button>
                <button class="control-btn pan-up" aria-label="Pan Up">&#8593;</button>
                <button class="control-btn pan-down" aria-label="Pan Down">&#8595;</button>
                <button class="control-btn pan-left" aria-label="Pan Left">&#8592;</button>
                <button class="control-btn pan-right" aria-label="Pan Right">&#8594;</button>
            </div>
        </section>
        <div class="info-panel">
            <button class="close-btn" aria-label="Close">&times;</button>
            <div class="info-content"></div>
        </div>
    </main>
</div>
